version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: victorwordpress
       MYSQL_DATABASE: wp
       MYSQL_USER: vdwp
       MYSQL_PASSWORD: 123456

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: vdwp
       WORDPRESS_DB_PASSWORD: 123456
volumes:
    db_data:


